### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Timong-craft** [Lopinosaurus/FloppyRecorder#1]
Sorry but I have python3 installed and first I can't clone the repo with your command (It must be `git clone https://github.com/Lopinosaurus/FloppyRecorder.git`)and if I download the files there is this: 
![image](https://user-images.githubusercontent.com/77288029/179350886-c5a82748-b807-48c9-9055-63ff62ca8ca7.png)

**Comment by Lopinosaurus** [comment]
Hello, thank you for your report !
Indeed, I made an error writing this command. I'll edit the README ASAP. Actually, the pip command is : 

python3 -m pip install -r requirements.txt

If the clone command does not work, you probably just do not have your ssh configured. You can clone by an other way running this command : 

git clone https://github.com/Lopinosaurus/FloppyRecorder.git

If you need help, do not hesitate to open an other issue, or add me on Discord : Lopinosaurus#0404
