### ISSUE TITLE
Feature Request/Idea

### ISSUE THREAD

**Issue by Timong-craft** [Lopinosaurus/FloppyRecorder#2]
1. Make an option to log the `Admin Server` too
2. Make an option to log the events in a own channel

Edit: 3. More Logs: user joins/lefts, voice logs, category and role logs

**Comment by Lopinosaurus** [comment]
The Admin Server is actually logged by the bot.
You must choose the channel where to log, by writing its ID in the ADMIN field in .env file

I chose not to log voice calls, but I might consider adding an option to log them. Role add, edit and deletion are not logged but member update are, so if a member add himself a new role you would eventually be warned by the bot. I will consider adding a feature to log role update, thank you !

**Comment by Timong-craft** [comment]
Ok, thanks
